import React from 'react'
import {
    Dimensions,
    StyleSheet,
    Platform,
    View,
    Text,
    ScrollView,
  } from "react-native";
  import colors from '../../../../config/color'
  import NorecordFound from '../../../../config/customComponents/custom_NoRecord_Found';
import TransactionListCard from '../../../../config/customComponents/custom_Transaction_List_Card';
import useDateAndMonth from '../../../../config/customHooks/useDateAndMonth';
import useDateAndMonthOutputText from '../../../../config/customHooks/useDateAndMonthOutputText';
import CustomStickeyAddButton from '../../../../config/customIcon/customStickeyAddButton';
const deviceWidth = Math.round(Dimensions.get("window").width);
const deviceHeight = Math.round(Dimensions.get("window").height);
import {styles} from '../DrawerPaymentRequestStyles/ManagePaymentStyles'
import CommonHigherOrderHeaderComponent from '../../../common_utilites/CommonHigherOrderHeaderComponent';
import PrimaryTransactionList from '../../PaymentRequestModule/TransactionComponent/PrimaryTransactionList';

const ManagePaymentLandingPage = (props)=>{
    const [monthNames, weekday] = useDateAndMonth();
    const data = [{
        "date": "25-09-2021",
        "data": [
            {
                "id": "910",
                "show_id": "3l8rj7eym1u19qdnbz064910",
                "transaction_type": null,
                "notes": "",
                "merchant_id": "4",
                "user_id": "412",
                "currency_code": "SGD",
                "pay_amount": "0.84",
                "total_paid": "0.00",
                "pay_type": "1",
                "trans_no": "",
                "secrat_key": "SparkingStar_83",
                "sign_id": "15bbacce8828dcb6c5a492cced77e60f",
                "transaction_id": null,
                "pay_status": "0",
                "remit_id": null,
                "trade_no": null,
                "status": "1",
                "created_at": "2021-09-25 16:07:18",
                "from_type": "1",
                "created_ip": "1976398999",
                "paid_at": null,
                "comm_amt": null,
                "comm_per": null,
                "plan_feeid": null,
                "refund_id": null,
                "created_by": "0",
                "paid_by": "0",
                "rfreq_by": "0",
                "cancel_by": "0",
                "device_id": "fb7a8c44-019d-441e-a8b7-0a215d995d59",
                "app_version": "1.1",
                "api_version": "1.0",
                "paid_json": null,
                "updated_at": null,
                "updated_ip": null,
                "plan_name": "STANDARD",
                "plan_feecode": "APOOUS",
                "fixed_fee": "0.00",
                "rate_fee": "2.20",
                "pf_id": "2",
                "merchant_name": "BEEP DIGITAL SOLUTIONS",
                "email_id": "DENNY@BEEP.SOLUTIONS",
                "user_fname": "Mohamed",
                "user_lname": "Fasith",
                "user_email": "harinimurali278@gmail.com",
                "user_mob": "123456"
            },
            {
                "id": "909",
                "show_id": "d893ex2tg4ia85csk7hv3909",
                "transaction_type": null,
                "notes": "",
                "merchant_id": "4",
                "user_id": "412",
                "currency_code": "SGD",
                "pay_amount": "0.84",
                "total_paid": "0.00",
                "pay_type": "1",
                "trans_no": "",
                "secrat_key": "PowefulSun_51",
                "sign_id": "98ad6118235e615d8e4c24e5103aa115",
                "transaction_id": null,
                "pay_status": "0",
                "remit_id": null,
                "trade_no": null,
                "status": "1",
                "created_at": "2021-09-25 16:05:21",
                "from_type": "1",
                "created_ip": "1976398999",
                "paid_at": null,
                "comm_amt": null,
                "comm_per": null,
                "plan_feeid": null,
                "refund_id": null,
                "created_by": "0",
                "paid_by": "0",
                "rfreq_by": "0",
                "cancel_by": "0",
                "device_id": "fb7a8c44-019d-441e-a8b7-0a215d995d59",
                "app_version": "1.1",
                "api_version": "1.0",
                "paid_json": null,
                "updated_at": null,
                "updated_ip": null,
                "plan_name": "STANDARD",
                "plan_feecode": "APOOUS",
                "fixed_fee": "0.00",
                "rate_fee": "2.20",
                "pf_id": "2",
                "merchant_name": "BEEP DIGITAL SOLUTIONS",
                "email_id": "DENNY@BEEP.SOLUTIONS",
                "user_fname": "Mohamed",
                "user_lname": "Fasith",
                "user_email": "harinimurali278@gmail.com",
                "user_mob": "123456"
            },
            {
                "id": "908",
                "show_id": "1tz8n6py7rdq98mk6x395908",
                "transaction_type": null,
                "notes": "",
                "merchant_id": "4",
                "user_id": "412",
                "currency_code": "SGD",
                "pay_amount": "0.84",
                "total_paid": "0.00",
                "pay_type": "1",
                "trans_no": "",
                "secrat_key": "GoodHeart_58",
                "sign_id": "b161ef60fa98ed09abe51192b172fa2c",
                "transaction_id": null,
                "pay_status": "0",
                "remit_id": null,
                "trade_no": null,
                "status": "1",
                "created_at": "2021-09-25 16:03:10",
                "from_type": "1",
                "created_ip": "1976398999",
                "paid_at": null,
                "comm_amt": null,
                "comm_per": null,
                "plan_feeid": null,
                "refund_id": null,
                "created_by": "0",
                "paid_by": "0",
                "rfreq_by": "0",
                "cancel_by": "0",
                "device_id": "fb7a8c44-019d-441e-a8b7-0a215d995d59",
                "app_version": "1.1",
                "api_version": "1.0",
                "paid_json": null,
                "updated_at": null,
                "updated_ip": null,
                "plan_name": "STANDARD",
                "plan_feecode": "APOOUS",
                "fixed_fee": "0.00",
                "rate_fee": "2.20",
                "pf_id": "2",
                "merchant_name": "BEEP DIGITAL SOLUTIONS",
                "email_id": "DENNY@BEEP.SOLUTIONS",
                "user_fname": "Mohamed",
                "user_lname": "Fasith",
                "user_email": "harinimurali278@gmail.com",
                "user_mob": "123456"
            },
            {
                "id": "907",
                "show_id": "zn80lgwd0p1i521uf695m907",
                "transaction_type": null,
                "notes": "",
                "merchant_id": "4",
                "user_id": "412",
                "currency_code": "SGD",
                "pay_amount": "0.84",
                "total_paid": "0.00",
                "pay_type": "1",
                "trans_no": "",
                "secrat_key": "PowefulSun_19",
                "sign_id": "0ff44a68ba11c0a775bb918ecf29f6e8",
                "transaction_id": null,
                "pay_status": "0",
                "remit_id": null,
                "trade_no": null,
                "status": "1",
                "created_at": "2021-09-25 15:59:39",
                "from_type": "1",
                "created_ip": "1976398999",
                "paid_at": null,
                "comm_amt": null,
                "comm_per": null,
                "plan_feeid": null,
                "refund_id": null,
                "created_by": "0",
                "paid_by": "0",
                "rfreq_by": "0",
                "cancel_by": "0",
                "device_id": "fb7a8c44-019d-441e-a8b7-0a215d995d59",
                "app_version": "1.1",
                "api_version": "1.0",
                "paid_json": null,
                "updated_at": null,
                "updated_ip": null,
                "plan_name": "STANDARD",
                "plan_feecode": "APOOUS",
                "fixed_fee": "0.00",
                "rate_fee": "2.20",
                "pf_id": "2",
                "merchant_name": "BEEP DIGITAL SOLUTIONS",
                "email_id": "DENNY@BEEP.SOLUTIONS",
                "user_fname": "Mohamed",
                "user_lname": "Fasith",
                "user_email": "harinimurali278@gmail.com",
                "user_mob": "123456"
            },
            {
                "id": "906",
                "show_id": "4dw19jbsovh4f85m35cr3906",
                "transaction_type": null,
                "notes": "",
                "merchant_id": "4",
                "user_id": "412",
                "currency_code": "SGD",
                "pay_amount": "0.84",
                "total_paid": "0.00",
                "pay_type": "1",
                "trans_no": "",
                "secrat_key": "SparkingStar_12",
                "sign_id": "57b0aaf14257ba5fa969382df37b708c",
                "transaction_id": null,
                "pay_status": "0",
                "remit_id": null,
                "trade_no": null,
                "status": "1",
                "created_at": "2021-09-25 15:59:01",
                "from_type": "1",
                "created_ip": "1976398999",
                "paid_at": null,
                "comm_amt": null,
                "comm_per": null,
                "plan_feeid": null,
                "refund_id": null,
                "created_by": "0",
                "paid_by": "0",
                "rfreq_by": "0",
                "cancel_by": "0",
                "device_id": "fb7a8c44-019d-441e-a8b7-0a215d995d59",
                "app_version": "1.1",
                "api_version": "1.0",
                "paid_json": null,
                "updated_at": null,
                "updated_ip": null,
                "plan_name": "STANDARD",
                "plan_feecode": "APOOUS",
                "fixed_fee": "0.00",
                "rate_fee": "2.20",
                "pf_id": "2",
                "merchant_name": "BEEP DIGITAL SOLUTIONS",
                "email_id": "DENNY@BEEP.SOLUTIONS",
                "user_fname": "Mohamed",
                "user_lname": "Fasith",
                "user_email": "harinimurali278@gmail.com",
                "user_mob": "123456"
            },
            {
                "id": "905",
                "show_id": "nk99s153a67yu0pjli483905",
                "transaction_type": null,
                "notes": "",
                "merchant_id": "4",
                "user_id": "412",
                "currency_code": "SGD",
                "pay_amount": "0.84",
                "total_paid": "0.00",
                "pay_type": "1",
                "trans_no": "",
                "secrat_key": "GoldenEagle_52",
                "sign_id": "40252027fdfbd7cb0d3140926535f825",
                "transaction_id": null,
                "pay_status": "0",
                "remit_id": null,
                "trade_no": null,
                "status": "1",
                "created_at": "2021-09-25 15:53:16",
                "from_type": "1",
                "created_ip": "1976398999",
                "paid_at": null,
                "comm_amt": null,
                "comm_per": null,
                "plan_feeid": null,
                "refund_id": null,
                "created_by": "0",
                "paid_by": "0",
                "rfreq_by": "0",
                "cancel_by": "0",
                "device_id": "fb7a8c44-019d-441e-a8b7-0a215d995d59",
                "app_version": "1.1",
                "api_version": "1.0",
                "paid_json": null,
                "updated_at": null,
                "updated_ip": null,
                "plan_name": "STANDARD",
                "plan_feecode": "APOOUS",
                "fixed_fee": "0.00",
                "rate_fee": "2.20",
                "pf_id": "2",
                "merchant_name": "BEEP DIGITAL SOLUTIONS",
                "email_id": "DENNY@BEEP.SOLUTIONS",
                "user_fname": "Mohamed",
                "user_lname": "Fasith",
                "user_email": "harinimurali278@gmail.com",
                "user_mob": "123456"
            },
            {
                "id": "904",
                "show_id": "mwjte843y2x2au5bl1vf0904",
                "transaction_type": null,
                "notes": "",
                "merchant_id": "4",
                "user_id": "412",
                "currency_code": "SGD",
                "pay_amount": "0.85",
                "total_paid": "0.00",
                "pay_type": "1",
                "trans_no": "",
                "secrat_key": "SparkingStar_46",
                "sign_id": "f750c059f7cac4c20a95760ad6050bbc",
                "transaction_id": null,
                "pay_status": "0",
                "remit_id": null,
                "trade_no": null,
                "status": "1",
                "created_at": "2021-09-25 15:46:23",
                "from_type": "1",
                "created_ip": "1976398999",
                "paid_at": null,
                "comm_amt": null,
                "comm_per": null,
                "plan_feeid": null,
                "refund_id": null,
                "created_by": "0",
                "paid_by": "0",
                "rfreq_by": "0",
                "cancel_by": "0",
                "device_id": "fb7a8c44-019d-441e-a8b7-0a215d995d59",
                "app_version": "1.1",
                "api_version": "1.0",
                "paid_json": null,
                "updated_at": null,
                "updated_ip": null,
                "plan_name": "STANDARD",
                "plan_feecode": "APOOUS",
                "fixed_fee": "0.00",
                "rate_fee": "2.20",
                "pf_id": "2",
                "merchant_name": "BEEP DIGITAL SOLUTIONS",
                "email_id": "DENNY@BEEP.SOLUTIONS",
                "user_fname": "Mohamed",
                "user_lname": "Fasith",
                "user_email": "harinimurali278@gmail.com",
                "user_mob": "123456"
            },
            {
                "id": "903",
                "show_id": "t9h1nwzi5b2dq6o4542vx903",
                "transaction_type": null,
                "notes": "",
                "merchant_id": "4",
                "user_id": "412",
                "currency_code": "SGD",
                "pay_amount": "0.87",
                "total_paid": "0.00",
                "pay_type": "1",
                "trans_no": "",
                "secrat_key": "PowefulSun_19",
                "sign_id": "9439328be23d2649354d5014a547ec36",
                "transaction_id": null,
                "pay_status": "0",
                "remit_id": null,
                "trade_no": null,
                "status": "1",
                "created_at": "2021-09-25 15:46:02",
                "from_type": "1",
                "created_ip": "1976398999",
                "paid_at": null,
                "comm_amt": null,
                "comm_per": null,
                "plan_feeid": null,
                "refund_id": null,
                "created_by": "0",
                "paid_by": "0",
                "rfreq_by": "0",
                "cancel_by": "0",
                "device_id": "fb7a8c44-019d-441e-a8b7-0a215d995d59",
                "app_version": "1.1",
                "api_version": "1.0",
                "paid_json": null,
                "updated_at": null,
                "updated_ip": null,
                "plan_name": "STANDARD",
                "plan_feecode": "APOOUS",
                "fixed_fee": "0.00",
                "rate_fee": "2.20",
                "pf_id": "2",
                "merchant_name": "BEEP DIGITAL SOLUTIONS",
                "email_id": "DENNY@BEEP.SOLUTIONS",
                "user_fname": "Mohamed",
                "user_lname": "Fasith",
                "user_email": "harinimurali278@gmail.com",
                "user_mob": "123456"
            },
            {
                "id": "902",
                "show_id": "36av6sb2wx0o8244t7ier902",
                "transaction_type": null,
                "notes": "",
                "merchant_id": "4",
                "user_id": "412",
                "currency_code": "SGD",
                "pay_amount": "0.87",
                "total_paid": "0.00",
                "pay_type": "1",
                "trans_no": "",
                "secrat_key": "SparkingStar_48",
                "sign_id": "b675bc4b28d3b507b493a477e4efe4f7",
                "transaction_id": null,
                "pay_status": "0",
                "remit_id": null,
                "trade_no": null,
                "status": "1",
                "created_at": "2021-09-25 15:43:59",
                "from_type": "1",
                "created_ip": "1976398999",
                "paid_at": null,
                "comm_amt": null,
                "comm_per": null,
                "plan_feeid": null,
                "refund_id": null,
                "created_by": "0",
                "paid_by": "0",
                "rfreq_by": "0",
                "cancel_by": "0",
                "device_id": "fb7a8c44-019d-441e-a8b7-0a215d995d59",
                "app_version": "1.1",
                "api_version": "1.0",
                "paid_json": null,
                "updated_at": null,
                "updated_ip": null,
                "plan_name": "STANDARD",
                "plan_feecode": "APOOUS",
                "fixed_fee": "0.00",
                "rate_fee": "2.20",
                "pf_id": "2",
                "merchant_name": "BEEP DIGITAL SOLUTIONS",
                "email_id": "DENNY@BEEP.SOLUTIONS",
                "user_fname": "Mohamed",
                "user_lname": "Fasith",
                "user_email": "harinimurali278@gmail.com",
                "user_mob": "123456"
            },
            {
                "id": "901",
                "show_id": "pb7gj2n6a85dxf7yi0l25901",
                "transaction_type": null,
                "notes": "",
                "merchant_id": "4",
                "user_id": "412",
                "currency_code": "SGD",
                "pay_amount": "0.85",
                "total_paid": "0.00",
                "pay_type": "1",
                "trans_no": "",
                "secrat_key": "GoldenEagle_57",
                "sign_id": "d04d9afa713c78467b95bd8cbfe912c2",
                "transaction_id": null,
                "pay_status": "0",
                "remit_id": null,
                "trade_no": null,
                "status": "1",
                "created_at": "2021-09-25 15:43:16",
                "from_type": "1",
                "created_ip": "1976398999",
                "paid_at": null,
                "comm_amt": null,
                "comm_per": null,
                "plan_feeid": null,
                "refund_id": null,
                "created_by": "0",
                "paid_by": "0",
                "rfreq_by": "0",
                "cancel_by": "0",
                "device_id": "fb7a8c44-019d-441e-a8b7-0a215d995d59",
                "app_version": "1.1",
                "api_version": "1.0",
                "paid_json": null,
                "updated_at": null,
                "updated_ip": null,
                "plan_name": "STANDARD",
                "plan_feecode": "APOOUS",
                "fixed_fee": "0.00",
                "rate_fee": "2.20",
                "pf_id": "2",
                "merchant_name": "BEEP DIGITAL SOLUTIONS",
                "email_id": "DENNY@BEEP.SOLUTIONS",
                "user_fname": "Mohamed",
                "user_lname": "Fasith",
                "user_email": "harinimurali278@gmail.com",
                "user_mob": "123456"
            },
            {
                "id": "900",
                "show_id": "2sw36l0nz5be773om0dpt900",
                "transaction_type": null,
                "notes": "",
                "merchant_id": "4",
                "user_id": "412",
                "currency_code": "SGD",
                "pay_amount": "0.85",
                "total_paid": "0.00",
                "pay_type": "1",
                "trans_no": "",
                "secrat_key": "GoldenEagle_15",
                "sign_id": "7ec7f4e7603ccc0bc05d6645cad7bae4",
                "transaction_id": null,
                "pay_status": "0",
                "remit_id": null,
                "trade_no": null,
                "status": "1",
                "created_at": "2021-09-25 15:36:57",
                "from_type": "1",
                "created_ip": "1976398999",
                "paid_at": null,
                "comm_amt": null,
                "comm_per": null,
                "plan_feeid": null,
                "refund_id": null,
                "created_by": "0",
                "paid_by": "0",
                "rfreq_by": "0",
                "cancel_by": "0",
                "device_id": "fb7a8c44-019d-441e-a8b7-0a215d995d59",
                "app_version": "1.1",
                "api_version": "1.0",
                "paid_json": null,
                "updated_at": null,
                "updated_ip": null,
                "plan_name": "STANDARD",
                "plan_feecode": "APOOUS",
                "fixed_fee": "0.00",
                "rate_fee": "2.20",
                "pf_id": "2",
                "merchant_name": "BEEP DIGITAL SOLUTIONS",
                "email_id": "DENNY@BEEP.SOLUTIONS",
                "user_fname": "Mohamed",
                "user_lname": "Fasith",
                "user_email": "harinimurali278@gmail.com",
                "user_mob": "123456"
            },
            {
                "id": "899",
                "show_id": "5z5031l6w7fbmd4siheu6899",
                "transaction_type": null,
                "notes": "",
                "merchant_id": "4",
                "user_id": "412",
                "currency_code": "SGD",
                "pay_amount": "0.85",
                "total_paid": "0.00",
                "pay_type": "1",
                "trans_no": "",
                "secrat_key": "SparkingStar_10",
                "sign_id": "d6a751f15b40ae47cdbdb69979c9ff1f",
                "transaction_id": null,
                "pay_status": "0",
                "remit_id": null,
                "trade_no": null,
                "status": "1",
                "created_at": "2021-09-25 15:36:16",
                "from_type": "1",
                "created_ip": "1976398999",
                "paid_at": null,
                "comm_amt": null,
                "comm_per": null,
                "plan_feeid": null,
                "refund_id": null,
                "created_by": "0",
                "paid_by": "0",
                "rfreq_by": "0",
                "cancel_by": "0",
                "device_id": "fb7a8c44-019d-441e-a8b7-0a215d995d59",
                "app_version": "1.1",
                "api_version": "1.0",
                "paid_json": null,
                "updated_at": null,
                "updated_ip": null,
                "plan_name": "STANDARD",
                "plan_feecode": "APOOUS",
                "fixed_fee": "0.00",
                "rate_fee": "2.20",
                "pf_id": "2",
                "merchant_name": "BEEP DIGITAL SOLUTIONS",
                "email_id": "DENNY@BEEP.SOLUTIONS",
                "user_fname": "Mohamed",
                "user_lname": "Fasith",
                "user_email": "harinimurali278@gmail.com",
                "user_mob": "123456"
            }]}]
    const status_obj =  {
                "0": "pending",
                "1": "Qr Generated",
                "2": "Confirmed or success",
                "3": "Refund Requested",
                "4": "Refunded",
                "5": "Refund Rejected",
                "9": "Failes"
            },
            
    renderItem = (item) => {
        console.log("item", item);
        const [date, H_M] = useDateAndMonthOutputText(item.created_at);
        
        return (
            <TransactionListCard
            status={"Alipay"}
            status_obj={status_obj}
            H_M={H_M}
            item={item}
            props={props}
            dateandTime={date}
            cardFrom={"ManagePayment"}
            />
        );
        };
    return(
        <View style={styles.container}>
        {console.log("datacomming repeat", data)}
        <PrimaryTransactionList
          data={data}
        //   refreshing={refreshing}
        //   onRefresh={onRefreshing}
          ListEmptyComponent={
            <View style={{ minHeight: deviceHeight }}>
              <NorecordFound />
            </View>
          }
          renderItem={({ item }) => renderItem(item)}
        //   onEndReached={()=>{
        //     if (!listerrorvalues) {
        //       loadMoreData();
        //     }
        //   }}
          renderSectionHeader={({ section: { date } }) => {
            let d = date.split("-");
            let dates = new Date(d[2], d[1] - 1, d[0]);
            return (
              <View style={{ backgroundColor: colors.date_bg }}>
                <Text style={styles.listHeaderDate}>
                  {weekday[dates.getDay()]}, {dates.getDate()}{" "}
                  {monthNames[dates.getMonth()].toUpperCase()}{" "}
                  {dates.getFullYear()}
                </Text>
              </View>
            );
          }}
        />
        <CustomStickeyAddButton
          onPress={props.navigation.navigate}
          navigationName={'CreatePaymentRequest'}
        />
        </View>
    )
}
const ModefiedManagePaymentLandingPage = (props)=>{
    return(
      <CommonHigherOrderHeaderComponent
      pagename={ManagePaymentLandingPage}
      headeronPress={() => console.log('hello')}
      headerTitle={"Manage Payments"}
      headerLeftIconType={"menu"}
      headerprops={props}
      {...props}
      />
    )
    }
export default ModefiedManagePaymentLandingPage