
import useCustomCategoryValidationYupHooks from "../defaultCategory/useCustomCategoryValidationYupHooks";
const useCustomManageServiceCategoryValidationYupHooks = useCustomCategoryValidationYupHooks
export default useCustomManageServiceCategoryValidationYupHooks;
